import streamlit as st

from predict import (
    predict_stock,
    get_price_history
)


# NIFTY 50 stocks

NIFTY_50 = {
    "Adani Enterprises": "ADANIENT.NS",
    "Adani Ports": "ADANIPORTS.NS",
    "Apollo Hospitals": "APOLLOHOSP.NS",
    "Asian Paints": "ASIANPAINT.NS",
    "Axis Bank": "AXISBANK.NS",
    "Bajaj Auto": "BAJAJ-AUTO.NS",
    "Bajaj Finance": "BAJFINANCE.NS",
    "Bajaj Finserv": "BAJAJFINSV.NS",
    "Bharat Electronics": "BEL.NS",
    "Bharti Airtel": "BHARTIARTL.NS",
    "Cipla": "CIPLA.NS",
    "Coal India": "COALINDIA.NS",
    "Dr. Reddy's Laboratories": "DRREDDY.NS",
    "Eicher Motors": "EICHERMOT.NS",
    "Eternal": "ETERNAL.NS",
    "Grasim Industries": "GRASIM.NS",
    "HCL Technologies": "HCLTECH.NS",
    "HDFC Bank": "HDFCBANK.NS",
    "HDFC Life": "HDFCLIFE.NS",
    "Hero MotoCorp": "HEROMOTOCO.NS",
    "Hindalco Industries": "HINDALCO.NS",
    "Hindustan Unilever": "HINDUNILVR.NS",
    "ICICI Bank": "ICICIBANK.NS",
    "IndusInd Bank": "INDUSINDBK.NS",
    "Infosys": "INFY.NS",
    "ITC": "ITC.NS",
    "Jio Financial Services": "JIOFIN.NS",
    "JSW Steel": "JSWSTEEL.NS",
    "Kotak Mahindra Bank": "KOTAKBANK.NS",
    "Larsen & Toubro": "LT.NS",
    "Mahindra & Mahindra": "M&M.NS",
    "Maruti Suzuki": "MARUTI.NS",
    "Max Healthcare": "MAXHEALTH.NS",
    "Nestle India": "NESTLEIND.NS",
    "NTPC": "NTPC.NS",
    "Oil & Natural Gas Corporation": "ONGC.NS",
    "Power Grid Corporation": "POWERGRID.NS",
    "Reliance Industries": "RELIANCE.NS",
    "SBI Life Insurance": "SBILIFE.NS",
    "State Bank of India": "SBIN.NS",
    "Shriram Finance": "SHRIRAMFIN.NS",
    "Sun Pharmaceutical": "SUNPHARMA.NS",
    "Tata Consultancy Services": "TCS.NS",
    "Tata Consumer Products": "TATACONSUM.NS",
    "Tata Motors": "TATAMOTORS.NS",
    "Tata Steel": "TATASTEEL.NS",
    "Tech Mahindra": "TECHM.NS",
    "Titan Company": "TITAN.NS",
    "Trent": "TRENT.NS",
    "UltraTech Cement": "ULTRACEMCO.NS",
    "Wipro": "WIPRO.NS",
    "Zomato": "ZOMATO.NS"
}


# Page configuration

st.set_page_config(
    page_title="NIFTY 50 Stock Predictor",
    page_icon="📈",
    layout="centered"
)


# Title

st.title("NIFTY 50 Stock Predictor")

st.write(
    "Predict the expected stock return over the next "
    "5 trading days using Linear Regression and Random Forest."
)


# Stock selection

stock_name = st.selectbox(
    "Select a NIFTY 50 stock",
    list(NIFTY_50.keys())
)

ticker = NIFTY_50[stock_name]


# Prediction

if st.button("Predict", type="primary"):

    with st.spinner(
        "Downloading market data and generating prediction..."
    ):

        try:

            result = predict_stock(ticker)

            st.success(
                "Prediction completed successfully."
            )

            st.subheader(stock_name)

            # Current price

            st.metric(
            "Current Price",
            f"₹{result['current_price']:.2f}"
            )

            st.divider()

            # Historical price chart

            st.subheader("6-Month Price History")

            price_history = get_price_history(ticker)

            st.line_chart(
                price_history["Close"]
            )

            st.divider()

            # Model predictions

            col1, col2 = st.columns(2)

            with col1:

                st.subheader("Linear Regression")

                st.metric(
                    "5-Day Return",
                    f"{result['linear_return'] * 100:.2f}%"
                )

                st.write(
                    "Predicted Price"
                )

                st.write(
                    f"₹{result['linear_price']:.2f}"
                )

            with col2:

                st.subheader("Random Forest")

                st.metric(
                    "5-Day Return",
                    f"{result['random_forest_return'] * 100:.2f}%"
                )

                st.write(
                    "Predicted Price"
                )

                st.write(
                    f"₹{result['random_forest_price']:.2f}"
                )

            st.divider()

            st.caption(
                f"Yahoo Finance ticker: {result['ticker']}"
            )

            st.info(
                "This prediction is generated by machine "
                "learning models for educational purposes "
                "and is not financial advice."
            )

        except Exception as e:

            st.error(
                f"Unable to generate prediction: {e}"
            )